-- --------------------------------------------------------
-- Hôte :                        localhost
-- Version du serveur:           5.7.24 - MySQL Community Server (GPL)
-- SE du serveur:                Win64
-- HeidiSQL Version:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Listage des données de la table kidsmovies.characters : ~8 rows (environ)
/*!40000 ALTER TABLE `characters` DISABLE KEYS */;
REPLACE INTO `characters` (`char_id`, `char_movie`, `char_name`, `char_img`, `char_desc`) VALUES
	(1, 1, 'Flash McQueen', 'cars_flash.jpg', 'Flash McQueen est une jeune voiture de course de type NASCAR conçue pour être rapide.'),
	(2, 1, 'Martin', 'cars_martin.jpg', 'Martin est le meilleur ami de Flash McQueen.'),
	(3, 3, 'Elsa', 'la_reine_des_neiges_elsa.jpg', 'Elsa est la reine du royaume d\'Arendelle, elle semble parfaite en tout point mais cache un terrible secret : elle possède la capacité de contrôler la neige et la glace!'),
	(4, 4, 'Tilt', '1001pattes_tilt.jpg', 'Tilt est une fourmi à l\'esprit un peu trop créatif. Il reçoit l’ordre d’arrêter ses inventions censées améliorer la productivité et de faire comme tout le monde. Il est soutenu par Couette, pour qui il a une grande affection...'),
	(5, 4, 'Couette', '1001pattes_couette.jpg', 'Le princesse Couette est la fille cadette de La Reine fourmi de la colonie des fourmis. Sa sœur aînée, Atta, est l\'héritière du trône. Couette est au départ la seule amie et partisane de Tilt. Elle est membre des Fourmis scouts, un groupe similaire à une troupe de scouts. Comme sa sœur et sa mère, elle a des ailes, mais elles ne sont pas encore complètement développées en raison de son âge.'),
	(6, 9, 'Toby', 'basil_detective_prive_toby.jpg', 'Toby est le chien du célèbre détective Sherlock Holmes, qui vit juste au-dessus de Basil au 221 Baker Street. La souris fait régulièrement appel au basset pour l\'aider à résoudre des enquêtes, en raison de l\'excellence de son flair.'),
	(7, 1, 'Sally', 'cars_sally.jpg', 'Sally Carrera, plus connue simplement en tant que Sally, est l\'avocate de la petite ville de Radiator Springs ainsi que la conjointe du célèbre bolide Flash McQueen.'),
	(8, 1, 'Doc Hudson', 'cars_dochudson.jpg', 'Doc Hudson, également connu en tant que Fabuleux Hudson Hornet, est un ancien coureur automobile devenu le médecin et le juge de la petite ville de Radiator Springs.');
/*!40000 ALTER TABLE `characters` ENABLE KEYS */;

-- Listage des données de la table kidsmovies.movies : ~79 rows (environ)
/*!40000 ALTER TABLE `movies` DISABLE KEYS */;
REPLACE INTO `movies` (`movie_id`, `movie_img`, `movie_title`, `movie_story`, `movie_suite`, `movie_date`, `movie_length`, `movie_url`) VALUES
	(1, 'https://s2.gaming-cdn.com/images/products/4054/orig/disney-pixar-cars-cover.jpg', 'Cars', 'Flash McQueen, splendide voiture de course promise au succès, doit participer à la prestigieuse Piston Cup. À cause d\'une déviation, Flash atterrit dans la petite ville de Radiator Springs, sur la Route 66. Il va alors rencontrer Sally, une élégante Porsche 2002, Doc Hudson, une Hudson Hornet 1951 au passé mystérieux, et Martin, une dépanneuse rouillée mais à qui on peut faire confiance.', 2, '2006', 117, 'cars'),
	(2, 'https://musicart.xboxlive.com/7/02361100-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080', 'Toy Story', 'Dans la chambre d\'Andy, ses jouets se mettent à vivre leur propre vie dès qu\'il sort de la pièce. Le jour de son anniversaire, quelques jours avant le déménagement de sa famille, c\'est la panique puisque chacun craint d\'être remplacé par un jouet neuf. Woody le cow-boy est le jouet préféré du jeune garçon et n\'appréhende donc pas tellement cette fête. Mais Andy reçoit une figurine articulée d\'astronaute, Buzz l\'Éclair. Très vite, il s\'avère que Woody a « perdu sa place » de jouet préféré, au profit de Buzz.', 1, '1995', 95, 'toy-story'),
	(3, 'https://fr.web.img5.acsta.net/pictures/210/521/21052146_20131023144339759.jpg', 'La reine des neiges', 'En juillet, au royaume d\'Arendelle. 3 ans après la mort de ses parents, la princesse Elsa est en âge de succéder à son père. Lorsque sa petite sœur Anna lui annonce son intention d\'épouser le prince Hans des Îles du Sud, elle refuse de lui donner son consentement. Face à l\'entêtement d\'Anna, la colère d\'Elsa lui fait révéler son grand secret ; elle possède le puissant pouvoir de contrôler la neige et la glace, avec lequel elle plonge involontairement et à son insu tout le royaume dans un hiver éternel, alors qu\'elle s\'enfuit dans les montagnes. Anna se lance dans un incroyable voyage pour retrouver Elsa et l\'avertir, afin qu\'elle inverse le processus.', 3, '2013', 109, 'la-reine-des-neiges'),
	(4, 'https://img.filmsactu.net/datas/films/1/0/1001-pattes/xl/46f880c5a2ffe.jpg', '1001 pattes', 'Tilt, fourmi quelque peu tête en l\'air, détruit par inadvertance la récolte de la saison. La fourmilière est dans tous ses états. En effet cette bévue va rendre fou de rage le Borgne, méchant insecte qui chaque été fait main basse sur une partie de la récolte avec sa bande de sauterelles racketteuses. Tilt décide de quitter l\'île pour recruter des mercenaires capables de chasser le Borgne.', 4, '1998', 95, '1001-pattes'),
	(5, 'https://images-na.ssl-images-amazon.com/images/I/61F14ZAHR6L._AC_SY445_.gif', 'Aladdin', 'Jafar, le grand vizir et conseiller du sultan de la ville d\'Agrabah, et son perroquet Iago, cherchent une lampe magique cachée dans la Caverne aux Merveilles. Ils apprennent qu\'une seule personne est digne d\'y entrer : « le diamant d\'innocence », qui se révèle être Aladdin, un jeune homme orphelin qui vit en volant de la nourriture aux marchands des souks. La princesse Jasmine d\'Agrabah, contrainte par la loi à devoir épouser un prince plutôt qu\'un homme qu\'elle aime, s\'échappe du palais et rencontre Aladdin ainsi que son singe de compagnie, Abu. Les gardes du palais capturent Aladdin sous les ordres de Jafar. Jasmine fait alors face à Jafar et demande à ce qu\'on libère Aladdin, mais Jafar ment et lui annonce qu\'Aladdin a été exécuté par décapitation. Déguisé en vieillard, Jafar libère Aladdin et Abu et les emmène jusqu\'à la Caverne, leur ordonnant de lui amener la lampe. À l\'intérieur, Aladdin rencontre un tapis volant, et trouve la lampe.', 5, '1992', 128, 'aladdin'),
	(6, 'https://fr.web.img3.acsta.net/pictures/20/03/16/16/20/2165756.jpg', 'Alice au pays des merveilles', 'Dans un parc, une jeune fille prénommée Alice, juchée sur un arbre, écoute de manière distraite sa sœur Anne lui faire une leçon d\'histoire tout en jouant avec son chat Dinah. Elle rêve d\'un monde plein de divagation où seuls des livres d\'images existeraient. Elle évoque ce monde imaginaire en chanson, allongée dans un champ de pâquerettes. C\'est alors que surgit un lapin blanc vêtu d\'une veste et portant une montre. Il se plaint d\'être en retard et entre dans un terrier, suivi par Alice qui souhaite se joindre à la fête. Elle tombe dans un trou, sa robe servant de parachute, croisant dans sa descente des meubles et des objets flottant dans l\'air...', 6, '1951', 75, 'alice-au-pays-des-merveilles'),
	(7, 'https://i0.wp.com/www.filmspourenfants.net/wp-content/uploads/2018/01/latlantide-lempire-perdu-a.jpg?fit=555%2C790&ssl=1', 'Atlantide l\'empire perdu', 'En 1914, Milo Thatch, expert linguiste et cartographe, travaille dans la chaufferie d\'un musée du Smithsonian Institution de Washington D.C. Tout comme l\'était son grand‑père Thaddeus Thatch, il est obsédé par la recherche du Manuscrit du Berger – ouvrage qui, d\'après la légende, n\'est autre qu\'un guide menant à l\'Atlantide, la fameuse cité engloutie. Alors qu\'il s\'apprête à présenter le résultat de ses recherches au comité du musée, ce dernier s\'arrange pour annuler la réunion car ses membres ne le prennent pas du tout au sérieux. Le soir même, alors que son moral est au plus bas, il est contacté par un milliardaire excentrique qui prévoit de financer une nouvelle expédition avec une équipe de talents pour aller découvrir l\'Atlantide, Milo est alors invité à faire partie de l\'équipe en tant qu\'expert de la mystérieuse cité.', 7, '2001', 96, 'atlantide-l-empire-perdu'),
	(8, 'https://www.ecranlarge.com/uploads/image/001/197/mqatafmu8fr4y6w8fcforu49bvn-051.jpg', 'Bambi', 'Dans la forêt, alors que le jour se lève, un oiseau bleu annonce à toute la forêt la naissance d\'un petit prince. Dans un bosquet d\'arbustes, une biche de l\'espèce des cerfs de Virginie vient de donner naissance à un faon. Réveillé par sa mère, ce dernier dit bonjour à tous les animaux regroupés en cercle autour de lui. Un jeune lapin, Panpan, remarque que le faon cherche à se mettre sur ses pattes mais qu\'il trébuche et tombe contre sa mère. Comme le fait remarquer le hibou, il manque de sommeil et les animaux laissent la mère et son petit. Panpan demande le nom du faon à sa mère, elle lui répond Bambi. Au loin un cerf couronné de grands bois observe la scène.', 8, '1942', 70, 'bambi'),
	(9, 'https://i.skyrock.net/1178/81191178/pics/3053064499_1_3_w91ZwMx9.jpg', 'Basil détective privé', 'Une nuit de l\'année 1897, alors que l\'inventeur Mr Flaversham célèbre l\'anniversaire de sa fille Olivia, une horrible créature proche de la chauve-souris interrompt la fête et kidnappe l\'inventeur. Terrorisée, Olivia part chercher de l\'aide auprès du célèbre détective Basil. Elle rencontre sur le chemin de Baker Street le Docteur David Q. Dawson, médecin militaire de retour d\'Afghanistan. Après avoir entendu son récit, Basil ne semble pas très intéressé jusqu\'au moment où il comprend que l\'auteur de l\'enlèvement ne peut être que Fidget, la chauve-souris, stupide mais fidèle serviteur, du professeur Ratigan. Ce dernier est un rat cruel et démoniaque, régnant sur les bas quartiers de Londres et qui n\'a pour but que de renverser la Reine des Souris au Palais de Buckingham. Basil décide alors de mener l\'enquête contre son ennemi de toujours pour sauver Mr Flaversham.', 9, '1986', 74, 'basil-detective-prive'),
	(10, 'https://i.pinimg.com/originals/d5/50/29/d5502975b8f1d2fad0c7f4348864d39b.jpg', 'Les aventures de Bernard et Bianca', 'Une jeune orpheline nommée Penny a été enlevée et enfermée dans un bateau à aube abandonné du Bayou du Diable. Un jour, elle jette à la mer une bouteille contenant un message de détresse et qui est découverte par la SOS Société, une organisation internationale de souris qui a élu domicile dans les caves du bâtiment des Nations unies. Miss Bianca, une souris blanche déléguée de Hongrie, se porte volontaire au secours de Penny. Après un temps d\'hésitation, le président de la SOS Société suggère de lui adjoindre un coéquipier. Ne sachant qui choisir entre les différents délégués masculins prêts à l\'accompagner, Bianca choisit finalement à la surprise générale Bernard, le concierge balbutiant atteint de triskaïdékaphobie.', 10, '1977', 77, 'les-aventures-de-bernard-et-bianca'),
	(11, 'https://vignette.wikia.nocookie.net/lemondededisney/images/3/3d/Bebapdk.jpg/revision/latest?cb=20181112172406&path-prefix=fr', 'Bernard et Bianca au pays des kangourous', 'En Australie, un jeune garçon, Cody, découvre où se trouve le nid d\'une aigle d\'Australie géante avant de se faire capturer par un braconnier, McLeach. Ce dernier kidnappe l\'enfant pour lui faire avouer où se trouve le nid de l\'aigle qu\'il espère capturer et revendre.', 10, '1990', 113, 'bernard-et-banca-au-pays-des-kangourous'),
	(12, 'https://i0.wp.com/www.filmspourenfants.net/wp-content/uploads/2018/02/blanche-neige-et-les-sept-nains-a-1.jpg?fit=555%2C785&ssl=1', 'Blanche-Neige et les sept nains', 'Blanche-Neige est une princesse vivant auprès de sa vaniteuse et malveillante belle-mère, la Reine. Courroucée et jalouse de la beauté de Blanche-Neige, elle l\'oblige à faire des tâches ménagères et à se vêtir de haillons. La Reine demande quotidiennement à son Miroir magique « Qui est la plus belle du royaume », et aime entendre en réponse qu\'il s\'agit d\'elle-même. Mais un jour, la Reine interrogeant son miroir, celui-ci lui répond que la plus belle du royaume est dorénavant la princesse Blanche-Neige. La Reine, désirant par dessus tout rester la femme la plus belle du royaume, ordonne alors à son fidèle chasseur d\'emmener la princesse Blanche-Neige dans les bois et de la tuer.', 11, '1937', 83, 'blanche-neige-et-les-sept-nains'),
	(13, 'https://fr.web.img5.acsta.net/medias/nmedia/18/71/72/07/19770156.jpg', 'Cars 2', 'Flash McQueen, la star des circuits automobiles, et son fidèle compagnon Martin la dépanneuse reprennent la route pour courir le tout premier Grand Prix Mondial, qui sacrera la voiture la plus rapide du monde ! Mais la route est pleine d\'imprévus, de déviations et de surprises, surtout lorsque Martin se retrouve entraîné dans une affaire d\'espionnage international !', 2, '2011', 106, 'cars-2'),
	(14, 'https://fr.web.img6.acsta.net/pictures/17/04/12/14/42/499210.jpg', 'Cars 3', 'Surpris par la nouvelle génération de voitures de course ultrarapides, le légendaire Flash McQueen est soudainement évincé du sport qu\'il aime tant. Afin de revenir dans le coup, il demande l\'aide de Cruz Ramirez, une jeune technicienne de course enthousiaste qui a son propre plan pour remporter la victoire, et prend quelques détours inattendus en cours de route.', 2, '2017', 102, 'cars-3'),
	(15, 'https://vignette.wikia.nocookie.net/disney-princesses/images/b/b5/Cendrillon_%28film%29.jpg/revision/latest/scale-to-width-down/340?cb=20130518174005&path-prefix=fr', 'Cendrillon', 'Cendrillon, une douce jeune fille, subit les méchancetés de sa belle-mère et de ses deux horribles filles. Un jour, transformée par sa marraine la bonne fée en princesse éclatante de beauté, elle se rend au bal du prince qui tombe fou amoureux d\'elle...', 12, '1950', 74, 'cendrillon'),
	(16, 'https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_.jpg', 'Coco', 'Depuis plusieurs générations, la musique est bannie dans la famille de Miguel. Un vrai déchirement pour le jeune garçon dont le rêve est de devenir un musicien aussi accompli que son idole, Ernesto de la Cruz. Bien décidé à prouver son talent, Miguel, par un étrange concours de circonstances, se retrouve propulsé dans un endroit aussi étonnant que coloré : le Pays des Morts. Là, il se lie d\'amitié avec Hector, un gentil garçon mais un peu filou sur les bords.', 13, '2017', 105, 'coco'),
	(17, 'https://musicart.xboxlive.com/7/13a91100-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080', 'Dumbo', 'Dumbo est un bébé éléphant pourvu d\'oreilles surdimensionnées, il est la risée de ses congénères jusqu\'au jour où il s\'aperçoit qu\'elles lui permettent de voler.', 14, '1941', 64, 'dumbo'),
	(18, 'https://fr.web.img2.acsta.net/pictures/20/01/06/14/00/1992182.jpg', 'En avant', 'Dans la banlieue d\'un univers imaginaire, deux frères elfes se lancent dans une quête extraordinaire pour découvrir s\'il reste encore un peu de magie dans le monde.', 15, '2020', 103, 'en-avant'),
	(19, 'https://vignette.wikia.nocookie.net/picsou/images/f/f2/Fantasia_2000.jpg/revision/latest?cb=20151029191439&path-prefix=fr', 'Fantasia 2000', '', 21, '1999', 75, 'fantasia-2000'),
	(20, 'https://fr.web.img6.acsta.net/medias/nmedia/18/78/92/34/19484162.jpg', 'Fantasia', '', 21, '1940', 125, 'fantasia'),
	(21, 'https://i0.wp.com/www.filmspourenfants.net/wp-content/uploads/2018/04/frere-des-ours-a.jpg?fit=555%2C788&ssl=1', 'Frère des ours', '', 16, '2003', 85, 'frere-des-ours'),
	(22, 'https://imageshack.com/a/img923/2068/9EuPQp.jpg', 'Hercule', '', 17, '1997', 89, 'hercule'),
	(23, 'https://i.skyrock.net/3092/84873092/pics/3107994645_1_3_MUMlmWZc.jpg', 'Kuzco', 'Kuzco est un jeune empereur inca très égoïste et capricieux. Pour ses dix-huit ans, il décide de raser un village afin de se faire construire une résidence, « Kuzcotopia ». Il décide par la même occasion de renvoyer sa conseillère Yzma mais celle-ci, avide de pouvoir, ne veut pas en rester là. Elle invite donc Kuzco à un dîner, afin de l\'empoisonner et de prendre sa place à la tête de l\'empire inca. Mais tout ne se passe pas comme prévu : Kuzco se retrouve transformé en lama.', 18, '2000', 75, 'kuzco'),
	(24, 'https://i0.wp.com/www.filmspourenfants.net/wp-content/uploads/2018/02/la-belle-au-bois-dormant-a-1.jpg?fit=555%2C687&ssl=1', 'La belle au bois dormant', '', 19, '1959', 75, 'la-belle-au-bois-dormant'),
	(25, 'https://i.pinimg.com/originals/41/cd/c8/41cdc87735e95a506ddcd02bd08dd8bd.jpg', 'La belle et la bête', '', 20, '1991', 87, 'la-belle-et-la-bete'),
	(26, 'https://i.pinimg.com/originals/91/53/87/91538734e27dedd8c4255eb602a33334.jpg', 'La belle et le clochard', '', 22, '1955', 75, 'la-belle-et-le-clochard'),
	(27, 'https://fr.web.img5.acsta.net/pictures/17/07/10/17/03/312097.jpg', 'La petite sirène', '', 23, '1989', 83, 'la-petite-sirene'),
	(28, 'https://i1.wp.com/www.filmspourenfants.net/wp-content/uploads/2018/05/la-planete-au-tresor-un-nouvel-univers-a.jpg?fit=555%2C762&ssl=1', 'La planète au trésor', '', 24, '2002', 95, 'la-planete-au-tresor'),
	(29, 'https://vignette.wikia.nocookie.net/princesse-disney/images/c/cb/Affiche_Disney_la-princesse-et-la-Grenouille.jpg/revision/latest/scale-to-width-down/340?cb=20120903165137&path-prefix=fr', 'La princesse et la grenouille', '', 25, '2009', 97, 'la-princesse-et-la-grenouille'),
	(30, 'https://fr.web.img6.acsta.net/pictures/19/10/25/15/08/5952325.jpg', 'La reine des neiges 2', '', 3, '2019', 103, 'la-reine-des-neiges-2'),
	(31, 'https://www.filmspourenfants.net/wp-content/uploads/2017/12/age-de-glace-1-a-350x500.jpg', 'L\'age de glace', '', 26, '2002', 85, 'l-age-de-glace'),
	(32, 'https://fr.web.img2.acsta.net/medias/nmedia/18/35/82/41/18603091.jpg', 'L\'age de glace 2', '', 26, '2006', 91, 'l-age-de-glace-2'),
	(33, 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcREBWFgacLA6KycEl_xYWqrs8Op-s6a1OaLig&usqp=CAU', 'L\'age de glace 3', '', 26, '2009', 94, 'l-age-de-glace-3'),
	(34, 'https://media.senscritique.com/media/000006380192/source_big/L_Age_de_glace_4_La_Derive_des_continents.jpg', 'L\'age de glace 4', '', 26, '2012', 88, 'l-age-de-glace-4'),
	(35, 'https://www.yvelines-infos.fr/content/uploads/2018/067515.jpg', 'L\'age de glace 5', '', 26, '2016', 94, 'l-age-de-glace-5'),
	(36, 'https://fr.web.img5.acsta.net/medias/nmedia/18/66/97/50/19104240.jpg', 'Là-haut', '', 27, '2009', 96, 'la-haut'),
	(37, 'https://fr.web.img6.acsta.net/pictures/210/111/21011147_20130607174439608.jpg', 'Le bossu de Notre-Dame', '', 28, '1996', 87, 'le-bossu-de-notre-dame'),
	(38, 'https://www.ecranlarge.com/uploads/image/001/123/uvyk7s8rape4ioxmtv5lgrs6ruz-891.jpg', 'Le livre de la jungle', '', 29, '1967', 78, 'le-livre-de-la-jungle'),
	(39, 'https://www.filmspourenfants.net/wp-content/uploads/2018/05/le-livre-de-la-jungle-2-a-366x500.jpg', 'Le livre de la jungle 2', '', 29, '2003', 72, 'le-livre-de-la-jungle-2'),
	(40, 'https://vignette.wikia.nocookie.net/lemondededisney/images/3/3c/Le-monde-de-dory.jpg/revision/latest?cb=20180712123801&path-prefix=fr', 'Le monde de Dory', '', 30, '2016', 97, 'le-monde-de-dory'),
	(41, 'https://i.pinimg.com/originals/e8/e6/e9/e8e6e93362a5deee5f10f24cf52fc5cd.jpg', 'Le monde de Némo', '', 30, '2003', 101, 'le-monde-de-nemo'),
	(42, 'https://i1.wp.com/www.filmspourenfants.net/wp-content/uploads/2018/06/le-roi-lion-a.jpg?fit=373%2C499&ssl=1', 'Le roi lion', '', 31, '1994', 89, 'le-roi-lion'),
	(43, 'https://i.pinimg.com/originals/a4/12/c0/a412c004e5e5f1d391a552c5b796f677.jpg', 'Le roi lion 2', '', 31, '1998', 78, 'le-roi-lion-2'),
	(44, 'https://www.filmspourenfants.net/wp-content/uploads/2018/06/le-roi-lion-3-a-357x500.jpg', 'Le roi lion 3', '', 31, '2004', 73, 'le-roi-lion-3'),
	(45, 'https://i.pinimg.com/originals/c0/9a/83/c09a836acdb552daeff20587dee34735.jpg', 'Le voyage d\'Arlo', '', 32, '2015', 94, 'le-voyage-d-arlo'),
	(46, 'https://fr.web.img4.acsta.net/medias/nmedia/18/65/83/79/20193459.jpg', 'Les 101 dalmatiens', '', 33, '1961', 79, 'les-101-dalmatiens'),
	(47, 'https://fr.web.img6.acsta.net/medias/nmedia/18/71/01/13/20193406.jpg', 'Les aristochats', '', 34, '1970', 78, 'les-aristochats'),
	(48, 'https://www.dvdfr.com/images/dvd/covers/200x280/ce97a6115fa6ec8e8ee4efe691b358c5/17132/old-indestructibles.0.jpg', 'Les indestructibles', '', 35, '2004', 115, 'les-indestructibles'),
	(49, 'https://fr.web.img6.acsta.net/pictures/18/04/13/15/09/0323902.jpg', 'Les indestructibles 2', '', 35, '2018', 118, 'les-indestructibles-2'),
	(50, 'https://www.ecranlarge.com/uploads/image/001/143/iofuhugy8kagruatnxitheyjuhh-575.jpg', 'Les mondes de Ralph', 'Ralph La Casse est l\'ennemi du jeu vidéo d\'arcade Fix it Felix Jr. C\'est un solide gaillard, il est de grande taille avec des bras massifs et son rôle est simpliste : à l\'aide de ses poings, il doit détruire un immeuble en brisant ses vitres et son revêtement. Pendant ce temps-là, Félix (le héros et personnage jouable par les humains) répare inlassablement les dégâts grâce à son marteau magique doré. Mais Ralph en a plus qu\'assez de vivre à part dans la décharge du jeu, seul et déprécié de tous.', 36, '2012', 108, 'les-mondes-de-ralph'),
	(51, 'https://vignette.wikia.nocookie.net/lemondededisney/images/8/8f/Ralph2.0.jpg/revision/latest?cb=20180712081855&path-prefix=fr', 'Ralph 2.0', '', 36, '2018', 112, 'ralph-2'),
	(52, 'https://fr.web.img6.acsta.net/medias/nmedia/18/62/89/46/18923316.jpg', 'L\'étrange Noël de Monsieur Jack', '', 37, '1993', 76, 'l-etrange-noel-de-monsieur-jack'),
	(53, 'https://i1.wp.com/www.filmspourenfants.net/wp-content/uploads/2018/06/lilo-et-stitch-a.jpg?fit=555%2C783&ssl=1', 'Lilo et Stitch', '', 38, '2002', 85, 'lilo-et-stitch'),
	(54, 'https://1.bp.blogspot.com/-CjCQikUkg_o/U0LMO5juU4I/AAAAAAAAFI0/QfsiyyCilBk/s1600/mary-poppins-1.jpg', 'Mary Poppins', '', 39, '1964', 139, 'mary-poppins'),
	(55, 'https://i0.wp.com/www.filmspourenfants.net/wp-content/uploads/2018/06/merlin-lenchanteur-a.jpg?fit=555%2C791&ssl=1', 'Merlin l\'enchanteur', '', 40, '1963', 79, 'merlin-l-enchanteur'),
	(56, 'https://fr.web.img4.acsta.net/medias/nmedia/00/02/36/12/affcie.jpg', 'Monstres et compagnie', '', 41, '2001', 92, 'monstres-et-compagnie'),
	(57, 'https://img.over-blog.com/382x500/0/19/49/05/2013/cinema/Monstres-Academy.jpg', 'Monstres Academy', '', 41, '2013', 102, 'monstres-academy'),
	(58, 'https://i0.wp.com/www.filmspourenfants.net/wp-content/uploads/2018/07/mulan-1-a.jpg?fit=555%2C801&ssl=1', 'Mulan', '', 42, '1998', 88, 'mulan'),
	(59, 'https://images-na.ssl-images-amazon.com/images/I/51D49Q3EX9L._AC_SY445_.jpg', 'Oliver et compagnie', '', 43, '1988', 73, 'oliver-et-compagnie'),
	(60, 'https://fr.web.img2.acsta.net/pictures/14/03/27/15/34/467713.jpg', 'Peter Pan', '', 44, '1953', 76, 'peter-pan'),
	(61, 'https://www.ecranlarge.com/uploads/image/001/124/3gf5euwvteb90kzblqnab4po7wt-223.jpg', 'Pinocchio', '', 45, '1940', 88, 'pinocchio'),
	(62, 'https://fr.web.img6.acsta.net/pictures/210/103/21010313_20130604174723216.jpg', 'Planes', '', 46, '2013', 92, 'planes'),
	(63, 'https://images-na.ssl-images-amazon.com/images/I/81my5WlsITL.jpg', 'Planes 2', '', 46, '2014', 83, 'planes-2'),
	(64, 'https://images-na.ssl-images-amazon.com/images/I/516GGD%2B02WL._AC_.jpg', 'Pocahontas', '', 47, '1995', 81, 'pocahontas'),
	(65, 'https://fr.web.img6.acsta.net/medias/nmedia/18/78/47/32/19539636.jpg', 'Raiponce', '', 48, '2010', 100, 'raiponce'),
	(66, 'https://i0.wp.com/www.filmspourenfants.net/wp-content/uploads/2018/07/ratatouille-a.jpg?fit=555%2C833&ssl=1', 'Ratatouille', '', 49, '2007', 111, 'ratatouille'),
	(67, 'https://fr.web.img6.acsta.net/medias/nmedia/18/84/94/35/20186089.jpg', 'Rebelle', '', 50, '2012', 93, 'rebelle'),
	(68, 'https://i.pinimg.com/originals/f4/32/5d/f4325da0a6622cbe7ce5a3f0317302d9.jpg', 'Robin des bois', '', 51, '1973', 83, 'robin-des-bois'),
	(69, 'https://i2.wp.com/www.filmspourenfants.net/wp-content/uploads/2018/07/rox-et-rouky-a.jpg?fit=555%2C777&ssl=1', 'Rox et Rouky', '', 52, '1981', 83, 'rox-et-rouky'),
	(70, 'https://ekladata.com/eRMOdFr2JBzeXVf7yJQ495dxlqs.jpg', 'Spirit l\'étalon des plaines', '', 53, '2002', 84, 'spirit-l-etalon-des-plaines'),
	(71, 'https://www.dvdfr.com/images/dvd/covers/457x640/352c789f13a1b7b496428ed433a2876a/11059/old-taram_et_le_chaudron_magique.0.jpg', 'Taram et le chaudron magique', '', 54, '1985', 80, 'taram-et-le-chaudron-magique'),
	(72, 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQmUUXcdLtB02M7rTISoWZ8FntBMGiv8_UXVg&usqp=CAU', 'Tarzan', '', 55, '1999', 88, 'tarzan'),
	(73, 'https://www.ecranlarge.com/uploads/image/001/121/ldosztevyoudrdo5nvoq4cq28al-211.jpg', 'Toy Story 2', '', 1, '1999', 93, 'toy-story-2'),
	(74, 'https://i.pinimg.com/originals/41/e9/9e/41e99e127f9d4760d43e55b48825be8e.jpg', 'Toy Story 3', '', 1, '2010', 103, 'toy-story-3'),
	(75, 'https://fr.web.img3.acsta.net/pictures/19/06/12/17/42/4485647.jpg', 'Toy Story 4', '', 1, '2019', 100, 'toy-story-4'),
	(76, 'https://images-na.ssl-images-amazon.com/images/I/617SBkUkj9L._AC_.jpg', 'Vaiana', '', 56, '2016', 107, 'vaiana'),
	(77, 'https://fr.web.img5.acsta.net/pictures/15/04/16/13/58/571071.jpg', 'Vice-versa', '', 57, '2015', 94, 'vice-versa'),
	(78, 'https://www.ecranlarge.com/uploads/image/001/126/lcf6qvz0n4tf8crudsegxnbycd3-490.jpg', 'Volt', 'Penny et son chien Volt sont les personnages principaux d\'une série canine à succès Volt où ils passent leur temps à échapper aux plans du diabolique Docteur Calico. Pour que cela soit le plus réaliste possible, les producteurs de l\'émission ont trompé Volt toute sa vie, en lui faisant croire que tout ce qui se passe dans la série est réel. Les distributeurs de la série trouvent le scénario trop prévisible, suivant un schéma classique où l\'héroïne est en danger puis sauvée in extremis par le chien héros. D\'ailleurs, dans les groupes de discussions, la tranche d\'âge 18-35 ans affirme ne pas aimer que cela se termine systématiquement bien. Ils décident alors que dans l\'épisode suivant Penny sera enlevée par le Docteur Calico. Une fois le tournage de cet épisode terminé, l\'agent de Penny ne la laisse pas aller voir Volt pour le calmer afin qu\'il continue de croire qu\'elle est entre les mains du Docteur Calico.', 58, '2008', 96, 'volt'),
	(79, 'https://fr.web.img5.acsta.net/medias/nmedia/18/63/93/01/18912032.jpg', 'Wall-E', '', 59, '2008', 98, 'wall-e'),
	(80, 'https://www.chroniquedisney.fr/imgAnimation/2000/2005-mulan2-1.jpg', 'Mulan 2', 'Alors que Mulan et Shang préparent activement leur mariage, l\'empereur de Chine les convoque et leur confie une mission de la plus haute importance : il s\'agit d\'escorter trois princesses et de les amener jusqu\'à leurs fiancés qui vivent à l\'autre bout du pays.', 42, '2004', 79, 'mulan-2'),
	(81, 'https://fr.web.img5.acsta.net/medias/nmedia/18/36/19/12/18460469.jpg', 'Bambi 2', 'Après la disparition de la mère de Bambi, son père, le Grand Prince de la Forêt, demande à Maître Hibou de trouver une biche pour s\'occuper du jeune faon. Mais en plein hiver, les biches ne peuvent pas trouver suffisamment à manger et le Prince accepte de s\'occuper de son fils jusqu\'au retour du printemps. Les jours passent et Bambi se retrouve souvent seul car il est difficile pour son père de surveiller la forêt si son fils est avec lui. Heureusement, il peut compter sur ses amis, Pan-Pan, Fleur et Féline.', 8, '2006', 72, 'bambi-2'),
	(82, 'https://media.senscritique.com/media/000008232553/source_big/Le_Retour_de_Jafar.jpg', 'Le retour de Jafar', ' ', 5, '1994', 69, 'le-retour-de-jafar'),
	(83, 'https://image.jeuxvideo.com/images-sm/pc/p/o/poglpc0f.jpg', 'La route d\'El Dorado', 'L\'histoire débute en 1519 à Séville (Espagne) où Tulio et Miguel, deux escrocs espagnols, viennent de gagner une partie de dés (en trichant) contre un homme qui a mis en jeu une carte censée mener à la légendaire cité de l\'or : Eldorado, également recherchée par Hernán Cortés, le chef des conquistadors qui s\'embarque le jour même pour le nouveau monde.', 60, '2000', 89, 'la-route-d-el-dorado');
/*!40000 ALTER TABLE `movies` ENABLE KEYS */;

-- Listage des données de la table kidsmovies.moviesuite : ~59 rows (environ)
/*!40000 ALTER TABLE `moviesuite` DISABLE KEYS */;
REPLACE INTO `moviesuite` (`suite_id`, `suite_title`) VALUES
	(1, 'Toy Story'),
	(2, 'Cars'),
	(3, 'La reine des neiges'),
	(4, '1001 pattes'),
	(5, 'Aladdin'),
	(6, 'Alice au payx des merveilles'),
	(7, 'Atlantide l\'empire perdu'),
	(8, 'Bambi'),
	(9, 'Basil détective privé'),
	(10, 'Bernard et Bianca'),
	(11, 'Blanche-Neige et les sept nains'),
	(12, 'Cendrillon'),
	(13, 'Coco'),
	(14, 'Dumbo'),
	(15, 'En avant'),
	(16, 'Frère des ours'),
	(17, 'Hercule'),
	(18, 'Kuzco'),
	(19, 'La belle au bois dormant'),
	(20, 'La belle et la bête'),
	(21, 'Fantasia'),
	(22, 'La belle et le Clochard'),
	(23, 'La petite sirène'),
	(24, 'La planète au trésor'),
	(25, 'La princesse et la grenouille'),
	(26, 'L\'âge de glace'),
	(27, 'Là-haut'),
	(28, 'Le bossu de Notre-Dame'),
	(29, 'Le livre de la jungle'),
	(30, 'Le monde Nemo'),
	(31, 'Le roi lion'),
	(32, 'Le voyage d\'Arlo'),
	(33, 'Les 101 dalmatiens'),
	(34, 'Les aristochats'),
	(35, 'Les indestructibles'),
	(36, 'Les mondes de Ralph'),
	(37, 'L\'étrange Noël de Monsieur Jack'),
	(38, 'Lilo et Stitch'),
	(39, 'Mary Poppins'),
	(40, 'Merlin l\'enchanteur'),
	(41, 'Monstres et compagnie'),
	(42, 'Mulan'),
	(43, 'Oliver et compagnie'),
	(44, 'Peter Pan'),
	(45, 'Pinocchio'),
	(46, 'Planes'),
	(47, 'Pocahontas'),
	(48, 'Raiponce'),
	(49, 'Ratatouille'),
	(50, 'Rebelle'),
	(51, 'Robin des bois'),
	(52, 'Rox et Rouky'),
	(53, 'Spirit l\'étalon des plaines'),
	(54, 'Taram et le chaudron magique'),
	(55, 'Tarzan'),
	(56, 'Vaiana'),
	(57, 'Vice-versa'),
	(58, 'Volt'),
	(59, 'Wall-E'),
	(60, 'La route d\'El Dorado');
/*!40000 ALTER TABLE `moviesuite` ENABLE KEYS */;

-- Listage des données de la table kidsmovies.songs : ~84 rows (environ)
/*!40000 ALTER TABLE `songs` DISABLE KEYS */;
REPLACE INTO `songs` (`song_id`, `song_movie`, `song_title`, `song_video`) VALUES
	(1, 1, 'Real gone', 'https://www.youtube.com/embed/WxptxCewdBo'),
	(2, 76, 'Pour les hommes', 'https://www.youtube.com/embed/Vuq_D7gFm_A'),
	(3, 76, 'Bling-bling', 'https://www.youtube.com/embed/bNMMpmpZBDY'),
	(4, 2, 'Je suis ton ami', 'https://www.youtube.com/embed/81dWdeDjfC4'),
	(5, 76, 'Le bleu lumière', 'https://www.youtube.com/embed/cDuwyrnVN4M'),
	(6, 76, 'Notre terre', 'https://www.youtube.com/embed/IVSeUmQMWR8'),
	(7, 76, 'L\'explorateur', 'https://www.youtube.com/embed/3WA34hxlejg'),
	(8, 76, 'Je suis Vaiana', 'https://www.youtube.com/embed/rSaQd4j0PGs'),
	(9, 76, 'Te Fiti', 'https://www.youtube.com/embed/K8pIF8EXnyA'),
	(10, 1, 'Life is a highway', 'https://www.youtube.com/embed/jURRsAMGuZk'),
	(11, 1, 'Our town', 'https://www.youtube.com/embed/fbHbRipzRgE'),
	(12, 1, 'Doc racing', 'https://www.youtube.com/embed/_ef17Xhnzxw'),
	(13, 2, 'Jamais plus je ne volerai', 'https://www.youtube.com/embed/gU9NdeOkRIc'),
	(14, 2, 'Etrange bizarre', 'https://www.youtube.com/embed/pT4YklQA7gM'),
	(15, 58, 'Comme un homme', 'https://www.youtube.com/embed/E-p6l9nioNI'),
	(16, 58, 'Réflexion', 'https://www.youtube.com/embed/KQd0ifv1yqc'),
	(17, 58, 'Une fille à aimer', 'https://www.youtube.com/embed/aQPTXmUJumg'),
	(18, 25, 'Histoire éternelle', 'https://www.youtube.com/embed/rQgjzwBkSeo'),
	(19, 25, 'Belle', 'https://www.youtube.com/embed/Vm7gj9vqBjY'),
	(20, 25, 'Gaston', 'https://www.youtube.com/embed/WeAWPIU5D_k'),
	(21, 25, 'C\'est la fête', 'https://www.youtube.com/embed/Xq3W-J7CZdk'),
	(22, 25, 'Prologue', 'https://www.youtube.com/embed/m-fsxPmddXE'),
	(23, 58, 'Honneur à tous', 'https://www.youtube.com/embed/bt65rqrVjO4'),
	(24, 5, 'Je suis ton meilleur ami', 'https://www.youtube.com/embed/N6ykVehoaeI'),
	(25, 5, 'Prince Ali', 'https://www.youtube.com/embed/H1Fv67HKdkQ'),
	(26, 65, 'Où est la vraie vie?', 'https://www.youtube.com/embed/KoFOaB9c8eI'),
	(27, 65, 'J\'ai un rêve', 'https://www.youtube.com/embed/_L8HUELtXBE'),
	(28, 65, 'Je veux y croire', 'https://www.youtube.com/embed/uf-9J5fooFE'),
	(29, 5, 'Je vole', 'https://www.youtube.com/embed/-SaJz9eBUEk'),
	(30, 5, 'Nuits d\'Arabie', 'https://www.youtube.com/embed/4y779NcKrLo'),
	(31, 5, 'Prince Ali (version Jafar)', 'https://www.youtube.com/embed/jNrzHPR-ckY'),
	(32, 29, 'Humain pour la vie', 'https://www.youtube.com/embed/DjXp0O6XAH4'),
	(33, 29, 'Creuser encore et encore', 'https://www.youtube.com/embed/oC7sOoyW1IY'),
	(34, 3, 'Nul n\'est parfait', 'https://www.youtube.com/embed/GDL7g0VA448'),
	(35, 3, 'Libérée, délivrée', 'https://www.youtube.com/embed/wQP9XZc2Y_c'),
	(36, 3, 'Je voudrais un bonhomme de neige', 'https://www.youtube.com/embed/3QAXFudxqRM'),
	(37, 3, 'Le renouveau', 'https://www.youtube.com/embed/xsqptzTAO4A'),
	(38, 3, 'En été', 'https://www.youtube.com/embed/xBPay2i_emc'),
	(39, 3, 'Le coeur de glace', 'https://www.youtube.com/embed/itGKy_jLdEw'),
	(40, 16, 'Un Poco Loco', 'https://www.youtube.com/embed/nDRCOf-o8VY'),
	(41, 16, 'La Llorona', 'https://www.youtube.com/embed/hAYUQ1ltJj0'),
	(42, 16, 'Proud Corazón', 'https://www.youtube.com/embed/sLkDCF_EbqI'),
	(43, 16, 'Ne m\'oublie pas', 'https://www.youtube.com/embed/NnDHlxuy9u0'),
	(44, 30, 'Je te cherche', 'https://www.youtube.com/embed/yfLQtedCh80'),
	(45, 30, 'Dans un autre monde', 'https://www.youtube.com/embed/AJ5SbhJKxu0'),
	(46, 30, 'Quand je serai plus grand', 'https://www.youtube.com/embed/34nnVqswt4c'),
	(47, 30, 'Point d\'avenir sans nous', 'https://www.youtube.com/embed/p7hn-PFjBHc'),
	(48, 56, 'Intro', 'https://www.youtube.com/embed/qWNIM_Gx9aU'),
	(49, 56, 'Si je ne t\'avais pas', 'https://www.youtube.com/embed/SPGejWoACXU'),
	(50, 17, 'Mon tout petit', 'https://www.youtube.com/embed/izwiy9nya9s'),
	(51, 17, 'Quand je vois voler un éléphant', 'https://www.youtube.com/embed/vyD_YbWB_JY'),
	(52, 24, 'J\'en ai rêvé', 'https://www.youtube.com/embed/qZivBdFJLk8'),
	(53, 24, 'Je voudrais', 'https://www.youtube.com/embed/AGdjHnBgnIU'),
	(54, 24, 'J\'en ai rêvé (final)', 'https://www.youtube.com/embed/GPVSBSsuLKY'),
	(55, 35, 'My superstar', 'https://www.youtube.com/embed/3DV7HkLNtjk'),
	(56, 35, 'Figaro', 'https://www.youtube.com/embed/bWX08RnzReI'),
	(57, 34, 'Capitaine Gutt', 'https://www.youtube.com/embed/nog0dU67VfY'),
	(58, 34, 'We are family', 'https://www.youtube.com/embed/j8pyXAY_CAs'),
	(59, 27, 'Sous l\'océan', 'https://www.youtube.com/embed/4iQETIfbzvk'),
	(60, 27, 'Partir là-bas', 'https://www.youtube.com/embed/_5KRPBFIboU'),
	(61, 27, 'Pour toi et moi', 'https://www.youtube.com/embed/A50ABApvWdU'),
	(62, 27, 'Pauvre âme en perdition', 'https://www.youtube.com/embed/RQGQDcz-jWI'),
	(63, 27, 'Les 6 filles du roi Triton', 'https://www.youtube.com/embed/arFFg11l7vw'),
	(64, 12, 'Siffler en travaillant', 'https://www.youtube.com/embed/YHU4fXw3a_U'),
	(65, 12, 'Heigh-Ho', 'https://www.youtube.com/embed/A70xUvyPA_c'),
	(66, 12, 'La tyrolienne des nains', 'https://www.youtube.com/embed/SShzwo_bbuk'),
	(67, 12, 'Un sourire en chantant', 'https://www.youtube.com/embed/ucTwPHYmGYg'),
	(68, 6, 'Le morse et le charpentier', 'https://www.youtube.com/embed/DVo3FqWk9l4'),
	(69, 6, 'Un joyeux non-anniversaire', 'https://www.youtube.com/embed/c9uneaTVFVU'),
	(70, 6, 'Un matin de mai fleuri', 'https://www.youtube.com/embed/I8gN0lcniug'),
	(71, 6, 'Peignons les roses en rouge', 'https://www.youtube.com/embed/nGFXi06f6V4'),
	(72, 6, 'Dans le monde de mes rêves', 'https://www.youtube.com/embed/lWUG1YFrffE'),
	(73, 27, 'Partir là-bas', 'https://www.youtube.com/embed/GPSO7H5I9QM'),
	(74, 5, 'Ce rêve bleu', 'https://www.youtube.com/embed/kGyS2-rZsC0'),
	(75, 20, 'Combat de dinosaures', 'https://www.youtube.com/embed/rfi7IDgVa5s'),
	(76, 30, 'J\'ai perdu le nord', 'https://www.youtube.com/embed/XLr9Mm0ZPQw'),
	(77, 30, 'Tout réparer', 'https://www.youtube.com/embed/hJFFa-0AzM8'),
	(78, 7, 'Transformation', 'https://www.youtube.com/embed/OUMU-uS0t6Y'),
	(79, 8, 'La chanson de la pluie', 'https://www.youtube.com/embed/m4wVf05X5GQ'),
	(80, 8, 'La chanson du printemps', 'https://www.youtube.com/embed/dzawbnjZDUg'),
	(81, 8, 'Je chante pour toi', 'https://www.youtube.com/embed/CmeCx4e8wjY'),
	(82, 59, 'Mais pourquoi m\'en faire?', 'https://www.youtube.com/embed/gaDkUDNzGw4'),
	(83, 59, 'Bonne compagnie', 'https://www.youtube.com/embed/ujUGovJW610'),
	(84, 59, 'La perfection, c\'est moi', 'https://www.youtube.com/embed/SFVHfppVb_k'),
	(85, 59, 'Il était une fois à New York City', 'https://www.youtube.com/embed/35t50ef2E0w'),
	(87, 59, 'Des rues en or', 'https://www.youtube.com/embed/e8_V1lyUs9I'),
	(88, 25, 'Madame Gaston', 'https://www.youtube.com/embed/EwP7mmMWkzo'),
	(89, 25, 'Je ne savais pas', 'https://www.youtube.com/embed/QvHBsX5iBKQ'),
	(90, 25, 'Tuons la bête', 'https://www.youtube.com/embed/mSZibqXQL3E');
/*!40000 ALTER TABLE `songs` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
